/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferParams, RuntimeNode } from '@parshjs/core';
import type { command as configSetKeyCmd } from './commands/config/set/[key].ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'config set [key]': {
      parents: {};
      rootOptions: {};
    };
    'config set [key] [value]': {
      parents: {
        'config set [key]': { options: {}; params: InferParams<typeof configSetKeyCmd.params> };
      };
      rootOptions: {};
    };
    'config show': {
      parents: {};
      rootOptions: {};
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: { path: '', optionNames: [], paramNames: [], load: () => import('./commands/_root.ts').then((m) => m.command) },
  literalChildren: {
    'config': {
      segment: { kind: 'literal', value: 'config' },
      command: null,
      literalChildren: {
        'set': {
          segment: { kind: 'literal', value: 'set' },
          command: null,
          literalChildren: {},
          paramChild: {
            segment: { kind: 'param', name: 'key' },
            command: { path: 'config set [key]', optionNames: [], paramNames: ['key'], hidden: true, load: () => import('./commands/config/set/[key].ts').then((m) => m.command) },
            literalChildren: {},
            paramChild: {
              segment: { kind: 'param', name: 'value' },
              command: { path: 'config set [key] [value]', optionNames: [], paramNames: ['value'], description: "Set a config value", load: () => import('./commands/config/set/[key]/[value].ts').then((m) => m.command) },
              literalChildren: {},
              paramChild: null,
            },
          },
        },
        'show': {
          segment: { kind: 'literal', value: 'show' },
          command: { path: 'config show', optionNames: [], paramNames: [], description: "Show current config", load: () => import('./commands/config/show.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: null,
    },
  },
  paramChild: null,
};
